# Generated by Django 6.0 on 2026-02-25 01:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCloudAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencies', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_wordcloud', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_wordcloud_aggregates',
            },
        ),
        migrations.CreateModel(
            name='AutoPhraseUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_auto_phrase_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_auto_phrase_usage',
                'indexes': [models.Index(fields=['user', 'usage_date'], name='journal_aut_user_id_de6c13_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'usage_date'), name='unique_user_autophrase_usage_date')],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('reflection_raw', models.TextField(blank=True, default='')),
                ('struggle_raw', models.TextField(blank=True, default='')),
                ('tomorrow_priority_raw', models.TextField(blank=True, default='')),
                ('gratitude_raw', models.TextField(blank=True, default='')),
                ('reflection_polished', models.TextField(blank=True, null=True)),
                ('struggle_polished', models.TextField(blank=True, null=True)),
                ('tomorrow_priority_polished', models.TextField(blank=True, null=True)),
                ('gratitude_polished', models.TextField(blank=True, null=True)),
                ('used_version', models.CharField(choices=[('raw', 'Raw'), ('polished', 'Polished'), ('mixed', 'Mixed')], default='raw', max_length=20)),
                ('sentiment_label', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('mixed', 'Mixed')], default='neutral', max_length=20)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('total_word_count', models.IntegerField(default=0)),
                ('field_word_counts', models.JSONField(blank=True, default=dict)),
                ('locked_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_entries',
                'ordering': ['-entry_date', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'entry_date'], name='journal_ent_user_id_a328f3_idx'), models.Index(fields=['user', 'updated_at'], name='journal_ent_user_id_1e8fd9_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'entry_date'), name='unique_user_entry_date')],
            },
        ),
    ]
