# Generated by Django 6.0 on 2026-02-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='full_day_input',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='parsed_via',
            field=models.CharField(choices=[('none', 'None'), ('ollama_frontend', 'Ollama Frontend'), ('manual', 'Manual')], default='none', max_length=30),
        ),
    ]
