# Generated by Django 6.0 on 2026-03-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_autophraseusage_feature'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='autophraseusage',
            name='journal_aut_user_id_de6c13_idx',
        ),
        migrations.RenameIndex(
            model_name='autophraseusage',
            new_name='journal_aut_user_id_81dcad_idx',
            old_name='journal_aut_user_id_eb5b8d_idx',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='parsed_via',
            field=models.CharField(choices=[('none', 'None'), ('ollama_frontend', 'Ollama Frontend'), ('backend_heuristic', 'Backend Heuristic'), ('manual', 'Manual')], default='none', max_length=30),
        ),
    ]
