# Generated by Django 6.0 on 2026-02-25 04:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goal', '0006_commitmentcontract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_type', models.CharField(choices=[('complete', 'Complete'), ('in_progress', 'In Progress')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('data_start_date', models.DateField()),
                ('data_end_date', models.DateField()),
                ('days_of_data', models.IntegerField(default=0)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='journey_books/pdf/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('privacy_settings', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_books', to='goal.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_number', models.IntegerField()),
                ('chapter_title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('is_projection', models.BooleanField(default=False)),
                ('ai_model_used', models.CharField(blank=True, max_length=100)),
                ('generation_time_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='journeybook.journeybook')),
            ],
        ),
        migrations.CreateModel(
            name='BookAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('completion_chart', 'Completion Chart'), ('sentiment_chart', 'Sentiment Chart'), ('streak_chart', 'Streak Chart'), ('heatmap', 'Heatmap'), ('wordcloud', 'Wordcloud'), ('milestone_timeline', 'Milestone Timeline'), ('placeholder_thematic', 'Placeholder Thematic')], max_length=40)),
                ('file_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='journeybook.journeybook')),
            ],
        ),
        migrations.CreateModel(
            name='DerivedMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('trigger_type', models.CharField(max_length=100)),
                ('achieved_date', models.DateField()),
                ('category', models.CharField(choices=[('discipline', 'Discipline'), ('career', 'Career'), ('health', 'Health'), ('personal', 'Personal'), ('writing', 'Writing')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'trigger_type'), name='journeybook_unique_user_trigger_type')],
            },
        ),
        migrations.AddIndex(
            model_name='journeybook',
            index=models.Index(fields=['user', 'status'], name='journeybook_user_id_04b750_idx'),
        ),
        migrations.AddIndex(
            model_name='journeybook',
            index=models.Index(fields=['user', 'goal'], name='journeybook_user_id_56a55e_idx'),
        ),
        migrations.AddIndex(
            model_name='journeybook',
            index=models.Index(fields=['created_at'], name='journeybook_created_3cbde6_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookchapter',
            constraint=models.UniqueConstraint(fields=('journey_book', 'chapter_number'), name='journeybook_unique_book_chapter_number'),
        ),
    ]
