# Generated by Django 6.0 on 2026-02-10 07:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTaskList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('completion_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_fully_completed', models.BooleanField(default=False, help_text='All tasks completed today')),
                ('completed_on_time', models.BooleanField(default=False, help_text='All tasks completed before midnight')),
                ('daily_motivation', models.TextField(blank=True)),
                ('daily_mantra', models.CharField(blank=True, help_text='Short motivational phrase for the day', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_task_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_task_lists',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak_days', models.IntegerField(default=0)),
                ('current_streak_start', models.DateField(blank=True, null=True)),
                ('longest_streak_days', models.IntegerField(default=0)),
                ('longest_streak_start', models.DateField(blank=True, null=True)),
                ('longest_streak_end', models.DateField(blank=True, null=True)),
                ('total_perfect_days', models.IntegerField(default=0, help_text='Total days with 100% task completion')),
                ('total_days_tracked', models.IntegerField(default=0)),
                ('last_updated', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discipline_streaks',
            },
        ),
        migrations.CreateModel(
            name='HabitTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='⭐', max_length=10)),
                ('why_important', models.TextField(blank=True, help_text='Why this habit is important for your goals')),
                ('frequency', models.CharField(choices=[('daily', 'Every Day'), ('weekdays', 'Weekdays Only'), ('custom', 'Custom Days')], default='daily', max_length=15)),
                ('custom_days', models.JSONField(blank=True, help_text='[0,1,2,3,4] for Mon-Fri if custom', null=True)),
                ('estimated_minutes', models.IntegerField(default=30)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_completions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to='goal.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habit_trackers',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HabitCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completion_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_minutes', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_completions', to=settings.AUTH_USER_MODEL)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='routine.habittracker')),
            ],
            options={
                'db_table': 'habit_completions',
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyTaskItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('habit', 'Daily Habit'), ('goal_task', 'Goal Task')], max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='✅', max_length=10)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('estimated_minutes', models.IntegerField(default=30, help_text='How long this takes')),
                ('actual_minutes', models.IntegerField(blank=True, help_text='How long it actually took', null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When it was completed (anytime today is fine!)', null=True)),
                ('suggested_time', models.TimeField(blank=True, help_text='Suggested time - NOT required to follow', null=True)),
                ('is_skipped', models.BooleanField(default=False)),
                ('skip_reason', models.TextField(blank=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('why_important', models.TextField(blank=True, help_text='Why completing this today matters')),
                ('display_order', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_task', models.ForeignKey(blank=True, help_text='Link to Task from goal hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_items', to='goal.task')),
                ('related_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_items', to='goal.goal')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='routine.dailytasklist')),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_items', to='routine.habittracker')),
            ],
            options={
                'db_table': 'daily_task_items',
                'ordering': ['task_list', '-priority', 'display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='dailytasklist',
            index=models.Index(fields=['user', 'date'], name='daily_task__user_id_0063f4_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytasklist',
            index=models.Index(fields=['user', 'is_fully_completed'], name='daily_task__user_id_e93075_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailytasklist',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='habitcompletion',
            unique_together={('habit', 'completion_date')},
        ),
        migrations.AddIndex(
            model_name='dailytaskitem',
            index=models.Index(fields=['task_list', 'is_completed'], name='daily_task__task_li_45e7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytaskitem',
            index=models.Index(fields=['task_list', 'priority'], name='daily_task__task_li_1306b0_idx'),
        ),
    ]
