# Generated by Django 6.0 on 2026-02-20 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_remove_goal_actual_completion_date_and_more'),
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailytaskitem',
            options={'ordering': ['task_list', 'display_order']},
        ),
        migrations.AddField(
            model_name='disciplinestreak',
            name='last_tracked_date',
            field=models.DateField(blank=True, help_text='The most recent date that was passed to update_streak().', null=True),
        ),
        migrations.AddField(
            model_name='habittracker',
            name='last_completed_date',
            field=models.DateField(blank=True, help_text='Last date the habit was completed. Used to detect streak breaks.', null=True),
        ),
        migrations.AlterField(
            model_name='dailytaskitem',
            name='actual_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailytaskitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailytaskitem',
            name='estimated_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='dailytaskitem',
            name='goal_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_items', to='goal.task'),
        ),
        migrations.AlterField(
            model_name='dailytaskitem',
            name='suggested_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailytaskitem',
            name='why_important',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailytasklist',
            name='completed_on_time',
            field=models.BooleanField(default=False, help_text='All tasks completed before midnight on the scheduled date'),
        ),
        migrations.AlterField(
            model_name='dailytasklist',
            name='daily_mantra',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dailytasklist',
            name='is_fully_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disciplinestreak',
            name='total_perfect_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habittracker',
            name='custom_days',
            field=models.JSONField(blank=True, help_text="List of weekday ints [0–6] where 0=Monday. Used when frequency='custom'.", null=True),
        ),
        migrations.AlterField(
            model_name='habittracker',
            name='why_important',
            field=models.TextField(blank=True),
        ),
    ]
