# Generated by Django 6.0 on 2026-02-23 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_dailytaskitem_time_slot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailytaskitem',
            new_name='daily_task__task_li_0f6cf5_idx',
            old_name='dti_tasklist_timeslot_idx',
        ),
    ]
