# Generated by Django 6.0 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routine", "0005_adaptive_roadmap_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailytasklist",
            name="schedule_constraints",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Event-aware scheduling metadata for routine-fit explanation.",
            ),
        ),
    ]
