# Generated by Django 6.0 on 2026-03-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0007_dailytaskitem_event_and_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='habittracker',
            name='ai_suggested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habittracker',
            name='category',
            field=models.CharField(choices=[('hydration', 'Hydration'), ('movement', 'Movement'), ('nutrition', 'Nutrition'), ('breathing', 'Breathing'), ('mental', 'Mental/Mindfulness'), ('sleep', 'Sleep'), ('other', 'Other')], default='other', max_length=15),
        ),
        migrations.AddField(
            model_name='habittracker',
            name='proof_metric_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='habittracker',
            name='reason_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='habittracker',
            name='reason_headline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='habittracker',
            name='rewards',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='habittracker',
            name='science_badge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='habittracker',
            name='suggested_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
