# Generated by Django 6.0 on 2026-03-06 06:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0008_habittracker_ai_suggested_habittracker_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bad_habits', models.JSONField(default=list)),
                ('conditions', models.JSONField(default=list)),
                ('on_medication', models.BooleanField(default=False)),
                ('condition_duration', models.CharField(blank=True, max_length=20)),
                ('job_type', models.CharField(blank=True, choices=[('desk', 'Desk/Office'), ('physical', 'Physical/Field'), ('creative', 'Creative'), ('healthcare', 'Healthcare'), ('student', 'Student'), ('freelance', 'Freelance')], max_length=20)),
                ('work_hours', models.CharField(blank=True, max_length=50)),
                ('sleep_pattern', models.CharField(blank=True, choices=[('early_riser', 'Early Riser'), ('night_owl', 'Night Owl'), ('irregular', 'Irregular'), ('shift_based', 'Shift-based')], max_length=20)),
                ('climate', models.CharField(blank=True, max_length=50)),
                ('budget_level', models.CharField(choices=[('minimal', 'Minimal (free only)'), ('low', 'Low ($1-20/mo)'), ('medium', 'Medium'), ('flexible', 'Flexible')], default='minimal', max_length=10)),
                ('age_range', models.CharField(blank=True, max_length=10)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('weight_goal', models.CharField(blank=True, max_length=30)),
                ('motivation_style', models.CharField(blank=True, choices=[('reward', 'Reward-driven'), ('progress', 'Progress tracking'), ('accountability', 'Accountability partner'), ('intrinsic', 'Intrinsic')], max_length=20)),
                ('willpower_level', models.CharField(choices=[('low', 'Low - need tiny habits'), ('medium', 'Medium'), ('high', 'High - push me')], default='medium', max_length=10)),
                ('stress_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('burnout', 'Burnout')], default='moderate', max_length=10)),
                ('past_failures', models.JSONField(default=list)),
                ('fitness_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light activity'), ('moderate', 'Moderate'), ('active', 'Active'), ('athletic', 'Athletic')], default='sedentary', max_length=15)),
                ('diet_type', models.CharField(blank=True, max_length=50)),
                ('food_restrictions', models.TextField(blank=True)),
                ('existing_habits', models.JSONField(default=list)),
                ('primary_goal', models.CharField(blank=True, max_length=100)),
                ('goal_timeframe', models.CharField(blank=True, max_length=20)),
                ('daily_time_available', models.CharField(blank=True, max_length=20)),
                ('commitment_words', models.TextField(blank=True)),
                ('commitment_person', models.CharField(blank=True, max_length=100)),
                ('commitment_emoji', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_profiles',
            },
        ),
    ]
