# Generated by Django 6.0 on 2026-03-06 06:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0006_commitmentcontract'),
        ('routine', '0009_healthprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(default='⭐', max_length=10)),
                ('category', models.CharField(choices=[('hydration', 'Hydration'), ('movement', 'Movement'), ('nutrition', 'Nutrition'), ('breathing', 'Breathing'), ('mental', 'Mental/Mindfulness'), ('sleep', 'Sleep'), ('other', 'Other')], default='other', max_length=15)),
                ('estimated_minutes', models.IntegerField(default=30)),
                ('suggested_time', models.TimeField(blank=True, null=True)),
                ('frequency', models.CharField(default='daily', max_length=15)),
                ('reason_headline', models.CharField(blank=True, max_length=200)),
                ('reason_body', models.TextField(blank=True)),
                ('science_badge', models.CharField(blank=True, max_length=100)),
                ('rewards', models.JSONField(default=list)),
                ('proof_metric_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('snoozed', 'Snoozed')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('snooze_until', models.DateField(blank=True, null=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('generation_batch', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit_tracker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_recommendation', to='routine.habittracker')),
                ('suggested_for_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habit_recommendations', to='goal.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habit_recommendations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='habit_recom_user_id_d81f35_idx'), models.Index(fields=['user', 'suggested_for_goal'], name='habit_recom_user_id_5d9c82_idx')],
            },
        ),
    ]
