# Generated by Django 6.0 on 2026-03-06 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0006_commitmentcontract'),
        ('routine', '0010_habitrecommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalProgressEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('metric_unit', models.CharField(max_length=20)),
                ('metric_direction', models.CharField(choices=[('up', 'Higher is better'), ('down', 'Lower is better')], default='up', max_length=5)),
                ('domain', models.CharField(choices=[('physical', 'Physical'), ('mental', 'Mental'), ('lifestyle', 'Lifestyle')], default='physical', max_length=15)),
                ('metric_start', models.FloatField(help_text='Day 1 value - denormalized for fast reads')),
                ('metric_target', models.FloatField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='goal.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_progress_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goal_progress_entries',
                'ordering': ['goal', 'date'],
                'indexes': [models.Index(fields=['user', 'date'], name='goal_progre_user_id_7e0a75_idx'), models.Index(fields=['goal', 'date'], name='goal_progre_goal_id_dea345_idx'), models.Index(fields=['goal', 'metric_name'], name='goal_progre_goal_id_becbb0_idx')],
                'unique_together': {('goal', 'date', 'metric_name')},
            },
        ),
    ]
