# Generated by Django 6.0 on 2026-03-06 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0011_goalprogressentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBrief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('brief_text', models.TextField()),
                ('habit_completion_yesterday', models.FloatField(default=0.0)),
                ('missed_habits_yesterday', models.JSONField(default=list)),
                ('goal_metrics_snapshot', models.JSONField(default=dict)),
                ('upcoming_events_today', models.JSONField(default=list)),
                ('streak_at_generation', models.IntegerField(default=0)),
                ('track_status', models.CharField(blank=True, choices=[('on_track', 'On Track'), ('behind', 'Slightly Behind'), ('struggling', 'Struggling')], max_length=15)),
                ('track_status_set_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_briefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_briefs',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
