# Generated by Django 6.0 on 2026-03-06 16:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0015_habitrecommendation_source_health_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytaskitem',
            name='item_type',
            field=models.CharField(choices=[('habit', 'Daily Habit'), ('goal_task', 'Goal Task'), ('event', 'Event'), ('journal', 'Journal')], max_length=15),
        ),
        migrations.CreateModel(
            name='RoutineDayModeCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('day_mode', models.CharField(choices=[('focused', 'Focused'), ('flex', 'Flex/Unplanned')], default='focused', max_length=10)),
                ('day_mode_note', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('explicit', 'Explicit request payload'), ('carry_forward', 'Carried from previous day'), ('default', 'Default focused mode')], default='default', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_day_mode_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'routine_day_mode_checkins',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='routine_day_user_id_205359_idx'), models.Index(fields=['user', 'day_mode'], name='routine_day_user_id_a22cc8_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
