# Generated by Django 6.0 on 2026-03-06 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0016_alter_dailytaskitem_item_type_routinedaymodecheckin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WakeInteraction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("local_date", models.DateField()),
                ("first_interaction_at", models.DateTimeField()),
                ("timezone_name", models.CharField(default="UTC", max_length=64)),
                ("source_path", models.CharField(blank=True, max_length=255)),
                ("source_method", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wake_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wake_interactions",
                "ordering": ["-local_date", "-first_interaction_at"],
                "unique_together": {("user", "local_date")},
            },
        ),
        migrations.CreateModel(
            name="WakeBaselineState",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("baseline_minutes", models.IntegerField(blank=True, null=True)),
                ("baseline_time", models.TimeField(blank=True, null=True)),
                ("baseline_timezone", models.CharField(default="UTC", max_length=64)),
                ("last_computed_at", models.DateTimeField(blank=True, null=True)),
                ("last_update_reason", models.CharField(blank=True, max_length=100)),
                ("last_sample_count", models.IntegerField(default=0)),
                ("last_valid_sample_count", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wake_baseline_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wake_baseline_states",
            },
        ),
        migrations.AddIndex(
            model_name="wakeinteraction",
            index=models.Index(fields=["user", "local_date"], name="wake_intera_user_id_45510d_idx"),
        ),
        migrations.AddIndex(
            model_name="wakeinteraction",
            index=models.Index(fields=["user", "first_interaction_at"], name="wake_intera_user_id_3813e6_idx"),
        ),
        migrations.AddIndex(
            model_name="wakebaselinestate",
            index=models.Index(fields=["baseline_timezone", "updated_at"], name="wake_baseli_baselin_13fe4a_idx"),
        ),
    ]
