# Generated by Django 6.0 on 2026-03-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0018_dailytaskitem_soft_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='habittracker',
            name='is_deletable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='habittracker',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habittracker',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10, null=True),
        ),
    ]
