# Generated by Django 6.0 on 2026-05-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rituals', '0002_ritualmessagehistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ritualmessagehistory',
            new_name='rituals_rit_user_id_8bed09_idx',
            old_name='rituals_rit_user_id_15f1e5_idx',
        ),
        migrations.RenameIndex(
            model_name='ritualmessagehistory',
            new_name='rituals_rit_user_id_af5777_idx',
            old_name='rituals_rit_user_id_3bd597_idx',
        ),
    ]
