# Generated by Django 6.0 on 2026-03-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communitydiscussion',
            new_name='community_d_categor_c9fc16_idx',
            old_name='community_d_categor_e4f057_idx',
        ),
        migrations.RenameIndex(
            model_name='communitydiscussion',
            new_name='community_d_is_pinn_d13997_idx',
            old_name='community_d_is_pinn_2f5df6_idx',
        ),
    ]
