# Generated by Django 6.0 on 2026-03-25 12:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=30)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Master preference toggle only; this does not guarantee notification delivery.')),
                ('routine_remainders', models.BooleanField(default=True)),
                ('streak_warnings', models.BooleanField(default=True)),
                ('personalize_assistant', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True, help_text='Preferred push channel if a feature supports it; not a delivery subscription.')),
                ('email_notifications', models.BooleanField(default=False, help_text='Preferred email channel if a feature supports it; not a delivery subscription.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, default='As an expert in AI application integration...', null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=50)),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('pro_monthly', 'Pro Monthly'), ('lifetime', 'Lifetime')], default='free', max_length=20)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('total_points', models.IntegerField(default=0)),
                ('current_level', models.IntegerField(default=1)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('nep', 'Nepal')], default='en', max_length=10)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'dark')], default='light', max_length=20)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('days_active', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPersonalDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_age', models.IntegerField(default=0, help_text='Current age', validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(100)])),
                ('date_of_birth', models.DateField(help_text='Your date of birth (used to calculate current age)')),
                ('roadmap_start_date', models.DateField(default=django.utils.timezone.now, help_text='When to start the roadmap (usually today)')),
                ('current_situation', models.TextField(help_text='\n        Describe your current situation:\n        - What are you doing now? (student, employed, unemployed, etc.)\n        - Where are you? (location, life stage)\n        - What\'s your current state? (skills, resources, constraints)\n        \n        Example: "I\'m a 25-year-old software developer in Nepal, earning $800/month. \n        I want to study Master\'s in AI in Australia and become a senior ML engineer. \n        I have basic Python skills but need to learn advanced ML. Limited budget but \n        strong family support."\n        ')),
                ('is_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_personal_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
