# Generated by Django 6.0 on 2026-01-04 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, default='As an expert in AI application integration...', null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('pro_monthly', 'Pro Monthly'), ('lifetime', 'Lifetime')], default='free', max_length=20)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('total_points', models.IntegerField(default=0)),
                ('current_level', models.IntegerField(default=1)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
