# Generated by Django 6.0 on 2026-02-18 02:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpersonaldetails',
            name='target_age',
        ),
        migrations.AddField(
            model_name='userpersonaldetails',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, help_text='Your date of birth (used to calculate current age)'),
            preserve_default=False,
        ),
    ]
