# Generated by Django 6.0 on 2026-01-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='days_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
