# Generated by Django 6.0 on 2026-02-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_userpersonaldetails_target_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='Asia/Kathmandu', max_length=50),
        ),
    ]
