# Generated by Django 6.0 on 2026-03-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_notifications',
            field=models.BooleanField(default=False, help_text='Preferred email channel if a feature supports it; not a delivery subscription.'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Master preference toggle only; this does not guarantee notification delivery.'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='push_notifications',
            field=models.BooleanField(default=True, help_text='Preferred push channel if a feature supports it; not a delivery subscription.'),
        ),
    ]
