# Generated by Django 6.0 on 2026-01-06 09:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_profile_preferred_language_alter_profile_theme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonalDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_age', models.IntegerField(help_text='Current age', validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(100)])),
                ('target_age', models.IntegerField(help_text='Age by which you want to achieve your goals', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(120)])),
                ('roadmap_start_date', models.DateField(default=django.utils.timezone.now, help_text='When to start the roadmap (usually today)')),
                ('current_situation', models.TextField(help_text='\n        Describe your current situation:\n        - What are you doing now? (student, employed, unemployed, etc.)\n        - Where are you? (location, life stage)\n        - What\'s your current state? (skills, resources, constraints)\n        \n        Example: "I\'m a 25-year-old software developer in Nepal, earning $800/month. \n        I want to study Master\'s in AI in Australia and become a senior ML engineer. \n        I have basic Python skills but need to learn advanced ML. Limited budget but \n        strong family support."\n        ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_personal_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
