# Generated by Django 6.0 on 2026-01-07 02:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_userpersonaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonaldetails',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpersonaldetails',
            name='current_age',
            field=models.IntegerField(default=0, help_text='Current age', validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userpersonaldetails',
            name='target_age',
            field=models.IntegerField(default=0, help_text='Age by which you want to achieve your goals', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
