# Generated by Django 6.0 on 2026-03-05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "event_type",
                    models.CharField(
                        choices=[("one_time", "One Time"), ("multi_day", "Multi Day"), ("recurring", "Recurring")],
                        max_length=20,
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("is_all_day", models.BooleanField(default=False)),
                ("timezone", models.CharField(max_length=64)),
                ("recurrence", models.JSONField(blank=True, null=True)),
                ("routine_constraint", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "db_table": "events",
                "ordering": ["start_at", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["user", "start_at"], name="events_user_start_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["user", "event_type"], name="events_user_type_idx"),
        ),
    ]
