# Generated by Django 6.0 on 2026-03-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='events_user_id_76edd0_idx',
            old_name='events_user_start_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_user_id_026379_idx',
            old_name='events_user_type_idx',
        ),
    ]
