# Generated by Django 6.0 on 2026-01-24 15:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('why_it_matters', models.TextField(help_text='Why this goal is important - shown to user for motivation')),
                ('key_skills', models.JSONField(blank=True, null=True)),
                ('primary_category', models.CharField(choices=[('financial', 'Financial'), ('career', 'Career'), ('health', 'Health'), ('personal', 'Personal')], max_length=50)),
                ('categories', models.JSONField(blank=True, default=list, help_text='\n        List of categories this goal belongs to. \n        Example: ["financial", "career", "personal"]\n        ')),
                ('impact_dimensions', models.JSONField(blank=True, default=dict, help_text="\n        Store how this goal affects different life areas:\n        {\n            'financial': {'weight': 0.8, 'target': 'Monthly revenue $10k',\n'current': 3500},\n            'career': {'weight': 0.9, 'target': 'Portfolio + Senior Dev\nskills'},\n            'health': {'weight': 0.3, 'target': 'Better work-life balance'},\n            'personal': {'weight': 0.6, 'target': 'Entrepreneurship\nconfidence'}\n        }\n        ", null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text="['side-business', 'passive-income', 'python', 'ai']", null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('ai_feasibility_score', models.FloatField(blank=True, help_text='AI-calculated feasibility score (0.0 to 1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ai_generation_context', models.TextField(blank=True, help_text='Context/reasoning behind AI-generated goal')),
                ('is_user_modified', models.BooleanField(default=False, help_text='True if user edited AI-generated goal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goals',
                'ordering': ['-priority', 'target_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalAttributes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_data', models.JSONField(blank=True, help_text="\n        {\n            'target_amount': 50000,\n            'current_amount': 15000,\n            'currency': 'USD',\n            'monthly_target': 5000,\n            'income_sources': ['salary', 'freelance', 'passive'],\n            'savings_rate': 0.3,\n            'investment_plan': 'Index funds',\n            'break_even_month': 6\n        }\n        ", null=True)),
                ('career_data', models.JSONField(blank=True, help_text="\n        {\n            'target_role': 'Senior Developer',\n            'target_company': 'FAANG',\n            'current_role': 'Mid-level Dev',\n            'skills_required': ['Python', 'AWS', 'Docker', 'System Design'],\n            'skills_current': ['Python', 'Django'],\n            'certifications_needed': ['AWS Solutions Architect'],\n            'networking_events_target': 12,\n            'portfolio_projects': ['Trading Bot', 'AI SaaS'],\n            'resume_updates_needed': true\n        }\n        ", null=True)),
                ('health_data', models.JSONField(blank=True, help_text="\n        {\n            'start_weight_kg': 85,\n            'target_weight_kg': 75,\n            'current_weight_kg': 80,\n            'start_body_fat_percent': 20,\n            'target_body_fat_percent': 12,\n            'current_body_fat_percent': 16,\n            'workout_frequency_per_week': 5,\n            'target_sleep_hours': 8,\n            'nutrition_plan': 'High protein, calorie deficit',\n            'measurements': {\n                'chest_cm': 100,\n                'waist_cm': 85,\n                'arms_cm': 35\n            }\n        }\n        ", null=True)),
                ('personal_data', models.JSONField(blank=True, help_text="\n        {\n            'books_target': 24,\n            'books_read': 8,\n            'current_reading': ['Atomic Habits'],\n            'relationships_to_strengthen': ['family', 'mentors'],\n            'hobbies': ['guitar', 'photography'],\n            'experiences_target': ['travel to Japan', 'learn diving'],\n            'confidence_level_current': 6,\n            'confidence_level_target': 9,\n            'public_speaking_events': 5\n        }\n        ", null=True)),
                ('skill_data', models.JSONField(blank=True, help_text="\n        {\n            'skill_name': 'Machine Learning',\n            'current_level': 'Intermediate',\n            'target_level': 'Advanced',\n            'courses': ['Coursera ML', 'Fast.ai'],\n            'courses_completed': 1,\n            'practice_hours_target': 200,\n            'practice_hours_current': 120,\n            'projects_completed': 3,\n            'certification_target': 'TensorFlow Developer'\n        }\n        ", null=True)),
                ('custom_data', models.JSONField(blank=True, help_text='Any other custom attributes specific to this goal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_processing_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_attributes', to='ai.aiprocessingjob')),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='goal.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Example: 'Master Python Fundamentals (January 2026)'", max_length=255)),
                ('description', models.TextField(blank=True, help_text="What you'll achieve: 'Learn data structures, algorithms, OOP concepts'")),
                ('success_criteria', models.TextField(blank=True, help_text="Example: 'Complete 50 LeetCode problems, build 2 Python projects, pass Python assessment'")),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Auto-calculated from subgoals', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('month_year', models.CharField(blank=True, help_text="Example: 'January 2026' or 'Q1 2026'", max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, help_text='Example: January 31, 2026', null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('estimated_duration_days', models.IntegerField(blank=True, default=30, help_text='Typically 30 days for monthly milestones', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='1 for January, 2 for February, etc.')),
                ('is_required', models.BooleanField(default=True, help_text='Some milestones might be optional based on progress')),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('ai_reasoning', models.TextField(blank=True, help_text="AI: 'Python fundamentals are essential foundation for ML interviews'")),
                ('is_user_modified', models.BooleanField(default=False)),
                ('is_user_added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on', models.ManyToManyField(blank=True, help_text='Prerequisites: Must complete Python before ML Algorithms', related_name='unlocks', to='goal.milestone')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='goal.goal')),
            ],
            options={
                'ordering': ['goal', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='SubGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Example: 'Week 1: Learn Data Structures (Lists, Tuples, Dicts, Sets)'", max_length=255)),
                ('description', models.TextField(blank=True, help_text="What to focus on: 'Study Python collections, practice manipulation, solve 10 problems'")),
                ('learning_objectives', models.JSONField(blank=True, default=list, help_text='["Master list operations", "Understand dict vs set", "Solve 10 data structure problems"]')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Auto-calculated from daily tasks', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('week_number', models.IntegerField(blank=True, help_text='Week 1, 2, 3, 4 of the month', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Example: January 1, 2026 (Monday)', null=True)),
                ('target_date', models.DateField(blank=True, help_text='Example: January 7, 2026 (Sunday)', null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('estimated_duration_days', models.IntegerField(default=7, help_text='Typically 7 days for weekly goals')),
                ('display_order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('ai_reasoning', models.TextField(blank=True, help_text="AI: 'Data structures are fundamental for coding interviews'")),
                ('is_user_modified', models.BooleanField(default=False)),
                ('is_user_added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgoals', to='goal.milestone')),
            ],
            options={
                'ordering': ['milestone', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Example: 'Study Python Lists - Read documentation + 2 hours practice'", max_length=255)),
                ('description', models.TextField(blank=True, help_text="What exactly to do: 'Read Python docs on lists, watch 30min tutorial, practice 10 operations'")),
                ('instructions', models.TextField(blank=True, help_text="Step-by-step: '1. Read docs 2. Watch video 3. Code along 4. Solve 5 problems'")),
                ('task_type', models.CharField(choices=[('learning', 'Learning'), ('practice', 'Practice'), ('project', 'Project'), ('review', 'Review'), ('assessment', 'Assessment')], default='learning', max_length=20)),
                ('resources', models.JSONField(blank=True, default=list, help_text='["https://docs.python.org/3/tutorial/datastructures.html", "LeetCode Easy Arrays"]')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, help_text='Example: January 1, 2026', null=True)),
                ('scheduled_time', models.TimeField(blank=True, help_text='Example: 09:00 AM', null=True)),
                ('estimated_duration_minutes', models.IntegerField(default=60, help_text='Example: 120 minutes (2 hours)')),
                ('actual_duration_minutes', models.IntegerField(blank=True, help_text='How long it actually took', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('completion_notes', models.TextField(blank=True, help_text="User's notes after completing: 'Learned list comprehensions, struggled with slicing'")),
                ('difficulty_rating', models.IntegerField(blank=True, help_text='1=Very Easy, 5=Very Hard', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('ai_reasoning', models.TextField(blank=True, help_text="AI: 'Lists are the most used data structure in Python interviews'")),
                ('is_user_modified', models.BooleanField(default=False)),
                ('is_user_added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subgoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='goal.subgoal')),
            ],
            options={
                'ordering': ['subgoal', 'scheduled_date', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='UserCurrentSituationGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_situation', models.JSONField()),
                ('current_role', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('key_skills', models.JSONField(blank=True, null=True)),
                ('main_goals', models.JSONField(blank=True, null=True)),
                ('time_availability', models.CharField(blank=True, max_length=255, null=True)),
                ('constraints', models.JSONField(blank=True, null=True)),
                ('priority_areas', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_processing_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_situation_goal', to='ai.aiprocessingjob')),
                ('user_personal_details', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_situation_goal', to='authentication.userpersonaldetails')),
            ],
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'primary_category'], name='goals_user_id_df0f40_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='goals_user_id_49fd29_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'target_date'], name='goals_user_id_8cf4d7_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['goal', 'status'], name='goal_milest_goal_id_53d641_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['goal', 'target_date'], name='goal_milest_goal_id_ad3a36_idx'),
        ),
        migrations.AddIndex(
            model_name='subgoal',
            index=models.Index(fields=['milestone', 'status'], name='goal_subgoa_milesto_f37876_idx'),
        ),
        migrations.AddIndex(
            model_name='subgoal',
            index=models.Index(fields=['milestone', 'start_date'], name='goal_subgoa_milesto_87df32_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['subgoal', 'status'], name='goal_task_subgoal_063b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['subgoal', 'scheduled_date'], name='goal_task_subgoal_52e250_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['scheduled_date', 'status'], name='goal_task_schedul_d7d177_idx'),
        ),
    ]
