# Generated by Django 6.0 on 2026-01-11 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCurrentSituationGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_situation', models.JSONField()),
                ('current_role', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('key_skills', models.JSONField(blank=True, null=True)),
                ('main_goals', models.JSONField(blank=True, null=True)),
                ('time_availability', models.CharField(blank=True, max_length=255, null=True)),
                ('constraints', models.JSONField(blank=True, null=True)),
                ('priority_areas', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_processing_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_situation_goal', to='ai.aiprocessingjob')),
            ],
        ),
    ]
