# Generated by Django 6.0 on 2026-01-14 01:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('why_it_matters', models.TextField(help_text='Why this goal is important - shown to user for motivation')),
                ('category', models.CharField(choices=[('financial', 'Financial'), ('career', 'Career'), ('health', 'Health'), ('personal', 'Personal')], max_length=50)),
                ('impact_dimensions', models.JSONField(blank=True, default=dict, help_text="\n        Store how this goal affects different life areas:\n        {\n            'financial': {'weight': 0.8, 'target': 'Monthly revenue $10k',\n'current': 3500},\n            'career': {'weight': 0.9, 'target': 'Portfolio + Senior Dev\nskills'},\n            'health': {'weight': 0.3, 'target': 'Better work-life balance'},\n            'personal': {'weight': 0.6, 'target': 'Entrepreneurship\nconfidence'}\n        }\n        ", null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text="['side-business', 'passive-income', 'python', 'ai']", null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('target_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('ai_feasibility_score', models.FloatField(blank=True, help_text='AI-calculated feasibility score (0.0 to 1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ai_generation_context', models.TextField(blank=True, help_text='Context/reasoning behind AI-generated goal')),
                ('is_user_modified', models.BooleanField(default=False, help_text='True if user edited AI-generated goal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goals',
                'ordering': ['-priority', 'target_date', 'created_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='goals_user_id_4d2e0e_idx'), models.Index(fields=['user', 'status'], name='goals_user_id_49fd29_idx'), models.Index(fields=['user', 'target_date'], name='goals_user_id_8cf4d7_idx')],
            },
        ),
    ]
