# Generated by Django 6.0 on 2026-02-19 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_userpersonaldetails_target_age_and_more'),
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='actual_completion_date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='key_skills',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='goalattributes',
            name='ai_processing_job',
        ),
        migrations.RemoveField(
            model_name='goalattributes',
            name='custom_data',
        ),
        migrations.RemoveField(
            model_name='goalattributes',
            name='skill_data',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='depends_on',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='estimated_duration_days',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='is_user_added',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='is_user_modified',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='month_year',
        ),
        migrations.RemoveField(
            model_name='subgoal',
            name='estimated_duration_days',
        ),
        migrations.RemoveField(
            model_name='subgoal',
            name='is_user_added',
        ),
        migrations.RemoveField(
            model_name='subgoal',
            name='learning_objectives',
        ),
        migrations.RemoveField(
            model_name='subgoal',
            name='week_number',
        ),
        migrations.RemoveField(
            model_name='task',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_user_added',
        ),
        migrations.RemoveField(
            model_name='task',
            name='resources',
        ),
        migrations.AddField(
            model_name='goal',
            name='ai_reasoning',
            field=models.TextField(blank=True, help_text='Why the AI generated or scored this goal the way it did.'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='impact_dimensions',
            field=models.JSONField(blank=True, default=dict, help_text="\n        Store how this goal affects different life areas:\n        {\n            'financial': {'weight': 0.8, 'target': 'Monthly revenue $10k',\n'current': 3500},\n            'career': {'weight': 0.9, 'target': 'Portfolio + Senior Dev\nskills'},\n            'health': {'weight': 0.3, 'target': 'Better work-life balance'},\n            'personal': {'weight': 0.6, 'target': 'Entrepreneurship\nconfidence'}\n        }\n        "),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='actual_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='How long it actually took', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Example: 120 minutes (2 hours)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='usercurrentsituationgoal',
            name='user_personal_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_situation_goal', to='authentication.userpersonaldetails'),
        ),
    ]
