# Generated by Django 6.0 on 2026-03-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='primary_category',
            field=models.CharField(choices=[('business', 'Business'), ('fitness', 'Fitness'), ('learning', 'Learning'), ('wellness', 'Wellness'), ('creative', 'Creative'), ('nutrition', 'Nutrition'), ('productivity', 'Productivity'), ('travel', 'Travel'), ('digital_habits', 'Digital Habits'), ('spiritual', 'Spiritual'), ('relationships', 'Relationships'), ('education', 'Education'), ('career', 'Career'), ('finance', 'Finance'), ('communication', 'Communication')], max_length=50),
        ),
    ]
