# Generated by Django 6.0 on 2026-02-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_remove_goal_actual_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='why_it_matters',
            field=models.JSONField(blank=True, default=list, help_text="List of reasons why this goal is important - shown to user for motivation. Example: ['Financial security', 'Career growth', 'Personal fulfillment']"),
        ),
    ]
