# Generated by Django 6.0 on 2026-01-14 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_data', models.JSONField(blank=True, help_text="\n        {\n            'target_amount': 50000,\n            'current_amount': 15000,\n            'currency': 'USD',\n            'monthly_target': 5000,\n            'income_sources': ['salary', 'freelance', 'passive'],\n            'savings_rate': 0.3,\n            'investment_plan': 'Index funds',\n            'break_even_month': 6\n        }\n        ", null=True)),
                ('career_data', models.JSONField(blank=True, help_text="\n        {\n            'target_role': 'Senior Developer',\n            'target_company': 'FAANG',\n            'current_role': 'Mid-level Dev',\n            'skills_required': ['Python', 'AWS', 'Docker', 'System Design'],\n            'skills_current': ['Python', 'Django'],\n            'certifications_needed': ['AWS Solutions Architect'],\n            'networking_events_target': 12,\n            'portfolio_projects': ['Trading Bot', 'AI SaaS'],\n            'resume_updates_needed': true\n        }\n        ", null=True)),
                ('health_data', models.JSONField(blank=True, help_text="\n        {\n            'start_weight_kg': 85,\n            'target_weight_kg': 75,\n            'current_weight_kg': 80,\n            'start_body_fat_percent': 20,\n            'target_body_fat_percent': 12,\n            'current_body_fat_percent': 16,\n            'workout_frequency_per_week': 5,\n            'target_sleep_hours': 8,\n            'nutrition_plan': 'High protein, calorie deficit',\n            'measurements': {\n                'chest_cm': 100,\n                'waist_cm': 85,\n                'arms_cm': 35\n            }\n        }\n        ", null=True)),
                ('personal_data', models.JSONField(blank=True, help_text="\n        {\n            'books_target': 24,\n            'books_read': 8,\n            'current_reading': ['Atomic Habits'],\n            'relationships_to_strengthen': ['family', 'mentors'],\n            'hobbies': ['guitar', 'photography'],\n            'experiences_target': ['travel to Japan', 'learn diving'],\n            'confidence_level_current': 6,\n            'confidence_level_target': 9,\n            'public_speaking_events': 5\n        }\n        ", null=True)),
                ('skill_data', models.JSONField(blank=True, help_text="\n        {\n            'skill_name': 'Machine Learning',\n            'current_level': 'Intermediate',\n            'target_level': 'Advanced',\n            'courses': ['Coursera ML', 'Fast.ai'],\n            'courses_completed': 1,\n            'practice_hours_target': 200,\n            'practice_hours_current': 120,\n            'projects_completed': 3,\n            'certification_target': 'TensorFlow Developer'\n        }\n        ", null=True)),
                ('custom_data', models.JSONField(blank=True, help_text='Any other custom attributes specific to this goal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='goal.goal')),
            ],
        ),
    ]
