# Generated by Django 6.0 on 2026-01-17 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('goal', '0003_goalattributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercurrentsituationgoal',
            name='user_personal_details',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_situation_goal', to='authentication.userpersonaldetails'),
        ),
    ]
