# Generated by Django 6.0 on 2026-01-17 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0005_alter_goal_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
