# Generated by Django 6.0 on 2026-01-20 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0006_alter_goal_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='goal',
            name='goals_user_id_4d2e0e_idx',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='category',
            new_name='primary_category',
        ),
        migrations.AddField(
            model_name='goal',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='\n        List of categories this goal belongs to. \n        Example: ["financial", "career", "personal"]\n        '),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'primary_category'], name='goals_user_id_df0f40_idx'),
        ),
    ]
