# Generated by Django 6.0 on 2026-03-08 15:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0006_commitmentcontract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='financial_current_saved',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='financial_feasibility_status',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('stretch', 'Stretch'), ('infeasible', 'Infeasible')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='financial_gap_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='financial_goal_type',
            field=models.CharField(blank=True, choices=[('property_real_estate', 'Property / Real Estate'), ('education', 'Education'), ('emergency_fund', 'Emergency Fund'), ('investment', 'Investment'), ('business_capital', 'Business Capital'), ('major_purchase', 'Major Purchase'), ('other', 'Other')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='financial_months_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='financial_required_monthly_savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='financial_target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='financial_timeline_flexibility',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('somewhat_flexible', 'Somewhat Flexible'), ('very_flexible', 'Very Flexible')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='UserFinancialProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employment_type', models.CharField(choices=[('student', 'Student'), ('aspiring_founder', 'Aspiring Founder'), ('early_career', 'Early Career'), ('salaried_employee', 'Salaried Employee'), ('freelancer', 'Freelancer'), ('business_owner', 'Business Owner'), ('between_jobs', 'Between Jobs')], max_length=30)),
                ('monthly_income_range', models.CharField(choices=[('none', 'None'), ('under_20k', 'Under 20k'), ('20k_50k', '20k-50k'), ('50k_1l', '50k-1L'), ('1l_3l', '1L-3L'), ('3l_plus', '3L+')], max_length=20)),
                ('monthly_surplus_range', models.CharField(choices=[('nothing_left', 'Nothing Left'), ('under_10k', 'Under 10k'), ('10k_30k', '10k-30k'), ('30k_70k', '30k-70k'), ('70k_plus', '70k+')], max_length=20)),
                ('primary_skill_area', models.CharField(choices=[('technology', 'Technology'), ('design', 'Design'), ('education', 'Education'), ('business', 'Business'), ('trade', 'Trade'), ('healthcare', 'Healthcare'), ('other', 'Other')], max_length=20)),
                ('total_current_savings_range', models.CharField(choices=[('none', 'None'), ('under_5l', 'Under 5L'), ('5l_20l', '5L-20L'), ('20l_50l', '20L-50L'), ('50l_plus', '50L+')], max_length=20)),
                ('needs_review', models.BooleanField(default=False)),
                ('review_reason', models.CharField(blank=True, default='', max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialProgressEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='First day of month')),
                ('planned_savings', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_savings', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('running_total_saved', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_progress_entries', to='goal.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_progress_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['month'],
                'constraints': [models.UniqueConstraint(fields=('goal', 'month'), name='unique_financial_progress_month')],
            },
        ),
        migrations.CreateModel(
            name='GoalLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('income_growth', 'Income Growth'), ('skill_building', 'Skill Building'), ('lifestyle', 'Lifestyle')], default='income_growth', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributing_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributing_links', to='goal.goal')),
                ('source_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_links', to='goal.goal')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_goal', 'contributing_goal'), name='unique_financial_goal_link')],
            },
        ),
    ]
