# Generated by Django 6.0 on 2026-01-20 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aiprocessingjob_user_raw_text'),
        ('goal', '0007_remove_goal_goals_user_id_4d2e0e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalattributes',
            name='ai_processing_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_attributes', to='ai.aiprocessingjob'),
        ),
    ]
