# Generated by Django 6.0 on 2026-03-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0008_task_generation_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekdays', 'Weekdays'), ('3x_per_week', '3x per week'), ('2x_per_week', '2x per week'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('event_triggered', 'Event Triggered'), ('once', 'Once')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='item_type',
            field=models.CharField(blank=True, choices=[('physical', 'Physical'), ('cognitive', 'Cognitive'), ('habit', 'Habit'), ('ritual', 'Ritual'), ('task', 'Task')], max_length=20, null=True),
        ),
    ]
