# Generated by Django 6.0 on 2026-01-22 01:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0008_goalattributes_ai_processing_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_blocking', models.BooleanField(default=True, help_text='If True, goal cannot start until dependency is completed')),
                ('sequence_gap_days', models.IntegerField(default=0, help_text='Minimum days gap between dependency completion and goal start')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depends_on_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_to', to='goal.goal')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_from', to='goal.goal')),
            ],
        ),
        migrations.CreateModel(
            name='SubGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('estimated_duration_days', models.IntegerField(blank=True, help_text='Estimated days to complete this subgoal', null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True, help_text='If False, completing this is optional')),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('ai_reasoning', models.TextField(blank=True, help_text='Why AI suggested this subgoal')),
                ('is_user_modified', models.BooleanField(default=False)),
                ('is_user_added', models.BooleanField(default=False, help_text='True if user manually added this subgoal (not AI)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgoals', to='goal.goal')),
            ],
        ),
        migrations.CreateModel(
            name='SubGoalDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_blocking', models.BooleanField(default=True, help_text='If True, subgoal cannot start until dependency is completed')),
                ('sequence_gap_days', models.IntegerField(default=0, help_text='Minimum days gap between dependency completion and subgoal start')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depends_on_subgoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_to', to='goal.subgoal')),
                ('subgoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_from', to='goal.subgoal')),
            ],
        ),
        migrations.CreateModel(
            name='SubGoalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='Specific step-by-step instructions or examples')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('estimated_duration_days', models.IntegerField(blank=True, help_text='Estimated days to complete this step', null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('ai_reasoning', models.TextField(blank=True, help_text='Why AI suggested this step')),
                ('is_user_modified', models.BooleanField(default=False)),
                ('is_user_added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subgoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='goal.subgoal')),
            ],
        ),
    ]
