# Generated by Django 6.0 on 2026-01-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0009_goaldependency_subgoal_subgoaldependency_subgoalstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgoal',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='subgoalstep',
            name='subgoal',
        ),
        migrations.RemoveField(
            model_name='subgoaldependency',
            name='subgoal',
        ),
        migrations.RemoveField(
            model_name='subgoaldependency',
            name='depends_on_subgoal',
        ),
        migrations.DeleteModel(
            name='GoalDependency',
        ),
        migrations.DeleteModel(
            name='SubGoalStep',
        ),
        migrations.DeleteModel(
            name='SubGoal',
        ),
        migrations.DeleteModel(
            name='SubGoalDependency',
        ),
    ]
