# Generated by Django 6.0 on 2026-01-24 05:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0010_remove_subgoal_goal_remove_subgoalstep_subgoal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Example: 'Master Python Fundamentals (January 2026)'", max_length=255)),
                ('description', models.TextField(blank=True, help_text="What you'll achieve: 'Learn data structures, algorithms, OOP concepts'")),
                ('success_criteria', models.TextField(blank=True, help_text="Example: 'Complete 50 LeetCode problems, build 2 Python projects, pass Python assessment'")),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Auto-calculated from subgoals', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('month_year', models.CharField(blank=True, help_text="Example: 'January 2026' or 'Q1 2026'", max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, help_text='Example: January 31, 2026', null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('estimated_duration_days', models.IntegerField(blank=True, default=30, help_text='Typically 30 days for monthly milestones', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='1 for January, 2 for February, etc.')),
                ('is_required', models.BooleanField(default=True, help_text='Some milestones might be optional based on progress')),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('ai_reasoning', models.TextField(blank=True, help_text="AI: 'Python fundamentals are essential foundation for ML interviews'")),
                ('is_user_modified', models.BooleanField(default=False)),
                ('is_user_added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on', models.ManyToManyField(blank=True, help_text='Prerequisites: Must complete Python before ML Algorithms', related_name='unlocks', to='goal.milestone')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='goal.goal')),
            ],
            options={
                'ordering': ['goal', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='SubGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Example: 'Week 1: Learn Data Structures (Lists, Tuples, Dicts, Sets)'", max_length=255)),
                ('description', models.TextField(blank=True, help_text="What to focus on: 'Study Python collections, practice manipulation, solve 10 problems'")),
                ('learning_objectives', models.JSONField(blank=True, default=list, help_text='["Master list operations", "Understand dict vs set", "Solve 10 data structure problems"]')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Auto-calculated from daily tasks', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('week_number', models.IntegerField(blank=True, help_text='Week 1, 2, 3, 4 of the month', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Example: January 1, 2026 (Monday)', null=True)),
                ('target_date', models.DateField(blank=True, help_text='Example: January 7, 2026 (Sunday)', null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('estimated_duration_days', models.IntegerField(default=7, help_text='Typically 7 days for weekly goals')),
                ('display_order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('ai_reasoning', models.TextField(blank=True, help_text="AI: 'Data structures are fundamental for coding interviews'")),
                ('is_user_modified', models.BooleanField(default=False)),
                ('is_user_added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgoals', to='goal.milestone')),
            ],
            options={
                'ordering': ['milestone', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Example: 'Study Python Lists - Read documentation + 2 hours practice'", max_length=255)),
                ('description', models.TextField(blank=True, help_text="What exactly to do: 'Read Python docs on lists, watch 30min tutorial, practice 10 operations'")),
                ('instructions', models.TextField(blank=True, help_text="Step-by-step: '1. Read docs 2. Watch video 3. Code along 4. Solve 5 problems'")),
                ('task_type', models.CharField(choices=[('learning', 'Learning'), ('practice', 'Practice'), ('project', 'Project'), ('review', 'Review'), ('assessment', 'Assessment')], default='learning', max_length=20)),
                ('resources', models.JSONField(blank=True, default=list, help_text='["https://docs.python.org/3/tutorial/datastructures.html", "LeetCode Easy Arrays"]')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, help_text='Example: January 1, 2026', null=True)),
                ('scheduled_time', models.TimeField(blank=True, help_text='Example: 09:00 AM', null=True)),
                ('estimated_duration_minutes', models.IntegerField(default=60, help_text='Example: 120 minutes (2 hours)')),
                ('actual_duration_minutes', models.IntegerField(blank=True, help_text='How long it actually took', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('completion_notes', models.TextField(blank=True, help_text="User's notes after completing: 'Learned list comprehensions, struggled with slicing'")),
                ('difficulty_rating', models.IntegerField(blank=True, help_text='1=Very Easy, 5=Very Hard', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('ai_reasoning', models.TextField(blank=True, help_text="AI: 'Lists are the most used data structure in Python interviews'")),
                ('is_user_modified', models.BooleanField(default=False)),
                ('is_user_added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subgoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='goal.subgoal')),
            ],
            options={
                'ordering': ['subgoal', 'scheduled_date', 'display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['goal', 'status'], name='goal_milest_goal_id_53d641_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['goal', 'target_date'], name='goal_milest_goal_id_ad3a36_idx'),
        ),
        migrations.AddIndex(
            model_name='subgoal',
            index=models.Index(fields=['milestone', 'status'], name='goal_subgoa_milesto_f37876_idx'),
        ),
        migrations.AddIndex(
            model_name='subgoal',
            index=models.Index(fields=['milestone', 'start_date'], name='goal_subgoa_milesto_87df32_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['subgoal', 'status'], name='goal_task_subgoal_063b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['subgoal', 'scheduled_date'], name='goal_task_subgoal_52e250_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['scheduled_date', 'status'], name='goal_task_schedul_d7d177_idx'),
        ),
    ]
