# Generated by Django 6.0 on 2026-01-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0011_milestone_subgoal_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='key_skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
