# Generated by Django 6.0 on 2026-03-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0012_goalcommitmentrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='goalcommitmentrecord',
            new_name='goal_commit_user_id_ba780e_idx',
            old_name='goal_commitm_user_id_ef18db_idx',
        ),
    ]
