# Generated by Django 6.0 on 2026-01-24 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0012_goal_key_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalattributes',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
