# Generated by Django 6.0 on 2026-03-10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GIESession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_text', models.TextField()),
                (
                    'goal_domain',
                    models.CharField(
                        choices=[
                            ('career', 'Career'),
                            ('health', 'Health'),
                            ('financial', 'Financial'),
                            ('learning', 'Learning'),
                            ('personal', 'Personal'),
                            ('business', 'Business'),
                            ('other', 'Other'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('ready_to_finalize', 'Ready To Finalize'),
                            ('finalized', 'Finalized'),
                            ('cancelled', 'Cancelled'),
                        ],
                        default='active',
                        max_length=20,
                    ),
                ),
                (
                    'phase',
                    models.CharField(
                        choices=[
                            ('intake', 'Intake'),
                            ('question_loop', 'Question Loop'),
                            ('review', 'Review'),
                            ('finalized', 'Finalized'),
                        ],
                        default='intake',
                        max_length=20,
                    ),
                ),
                ('current_question', models.TextField(blank=True, null=True)),
                ('required_slot_count', models.IntegerField(default=0)),
                ('filled_required_slot_count', models.IntegerField(default=0)),
                ('completeness_percent', models.FloatField(default=0.0)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='gie_sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'gie_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GIEPlanSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'status',
                    models.CharField(
                        choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('superseded', 'Superseded')],
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('goal_summary', models.TextField()),
                ('assumptions', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('milestones', models.JSONField(blank=True, default=list)),
                ('weekly_routine_guidance', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='plan_snapshots',
                        to='gie.giesession',
                    ),
                ),
            ],
            options={
                'db_table': 'gie_plan_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GIESlotDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('required', models.BooleanField(default=False)),
                (
                    'data_type',
                    models.CharField(
                        choices=[
                            ('string', 'String'),
                            ('number', 'Number'),
                            ('integer', 'Integer'),
                            ('boolean', 'Boolean'),
                            ('date', 'Date'),
                            ('enum', 'Enum'),
                            ('list_string', 'List String'),
                        ],
                        max_length=20,
                    ),
                ),
                ('enum_values', models.JSONField(blank=True, null=True)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='slot_definitions',
                        to='gie.giesession',
                    ),
                ),
            ],
            options={
                'db_table': 'gie_slot_definitions',
                'ordering': ['required', 'key'],
            },
        ),
        migrations.CreateModel(
            name='GIESlotState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_key', models.CharField(max_length=120)),
                ('required', models.BooleanField(default=False)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('missing', 'Missing'),
                            ('partial', 'Partial'),
                            ('filled', 'Filled'),
                            ('locked', 'Locked'),
                        ],
                        default='missing',
                        max_length=20,
                    ),
                ),
                ('value', models.JSONField(blank=True, null=True)),
                (
                    'source',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('goal_text', 'Goal Text'),
                            ('turn_answer', 'Turn Answer'),
                            ('inference', 'Inference'),
                            ('system_default', 'System Default'),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('last_updated_turn_index', models.PositiveIntegerField(blank=True, null=True)),
                ('missing_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='slot_states',
                        to='gie.giesession',
                    ),
                ),
            ],
            options={
                'db_table': 'gie_slot_states',
                'ordering': ['slot_key'],
            },
        ),
        migrations.CreateModel(
            name='GIETurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_index', models.PositiveIntegerField()),
                (
                    'role',
                    models.CharField(
                        choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')],
                        max_length=20,
                    ),
                ),
                (
                    'kind',
                    models.CharField(
                        choices=[
                            ('goal_statement', 'Goal Statement'),
                            ('slot_answer', 'Slot Answer'),
                            ('followup_question', 'Followup Question'),
                            ('clarification', 'Clarification'),
                            ('confirmation', 'Confirmation'),
                        ],
                        max_length=30,
                    ),
                ),
                ('content', models.TextField()),
                ('client_turn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='turns',
                        to='gie.giesession',
                    ),
                ),
            ],
            options={
                'db_table': 'gie_turns',
                'ordering': ['turn_index', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='giesession',
            index=models.Index(fields=['user', 'status'], name='gie_session_user_id_153751_idx'),
        ),
        migrations.AddIndex(
            model_name='giesession',
            index=models.Index(fields=['user', 'phase'], name='gie_session_user_id_290759_idx'),
        ),
        migrations.AddIndex(
            model_name='giesession',
            index=models.Index(fields=['user', '-updated_at'], name='gie_session_user_id_a1c428_idx'),
        ),
        migrations.AddIndex(
            model_name='gieplansnapshot',
            index=models.Index(fields=['session', 'status', '-created_at'], name='gie_plan_sn_session_cbf443_idx'),
        ),
        migrations.AddIndex(
            model_name='gieslotdefinition',
            index=models.Index(fields=['session', 'required'], name='gie_slot_de_session_487ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='gieslotdefinition',
            index=models.Index(fields=['session', 'data_type'], name='gie_slot_de_session_199bac_idx'),
        ),
        migrations.AddConstraint(
            model_name='gieslotdefinition',
            constraint=models.UniqueConstraint(fields=('session', 'key'), name='unique_gie_slot_definition_key_per_session'),
        ),
        migrations.AddIndex(
            model_name='gieslotstate',
            index=models.Index(fields=['session', 'status'], name='gie_slot_st_session_ffd55e_idx'),
        ),
        migrations.AddIndex(
            model_name='gieslotstate',
            index=models.Index(fields=['session', 'required'], name='gie_slot_st_session_a02585_idx'),
        ),
        migrations.AddConstraint(
            model_name='gieslotstate',
            constraint=models.UniqueConstraint(fields=('session', 'slot_key'), name='unique_gie_slot_state_key_per_session'),
        ),
        migrations.AddIndex(
            model_name='gieturn',
            index=models.Index(fields=['session', 'turn_index'], name='gie_turns_session_1702b3_idx'),
        ),
        migrations.AddIndex(
            model_name='gieturn',
            index=models.Index(fields=['session', 'created_at'], name='gie_turns_session_f3ffc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='gieturn',
            constraint=models.UniqueConstraint(fields=('session', 'turn_index'), name='unique_gie_turn_index_per_session'),
        ),
        migrations.AddConstraint(
            model_name='gieturn',
            constraint=models.UniqueConstraint(
                condition=models.Q(client_turn_id__isnull=False),
                fields=('session', 'client_turn_id'),
                name='unique_gie_client_turn_id_per_session',
            ),
        ),
    ]
