# Generated by Django 6.0 on 2026-03-12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GIEAdaptationProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'trigger',
                    models.CharField(
                        choices=[
                            ('missed_tasks_streak', 'Missed Tasks Streak'),
                            ('declining_engagement', 'Declining Engagement'),
                            ('negative_sentiment', 'Negative Sentiment'),
                            ('stalled_progress', 'Stalled Progress'),
                            ('timeline_change', 'Timeline Change'),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('reduce_scope', 'Reduce Scope'),
                            ('resequence_milestones', 'Resequence Milestones'),
                            ('increase_support', 'Increase Support'),
                            ('adjust_timeline', 'Adjust Timeline'),
                            ('swap_commitment', 'Swap Commitment'),
                        ],
                        max_length=40,
                    ),
                ),
                ('reason', models.TextField()),
                ('changes', models.JSONField(blank=True, default=list)),
                ('recommended_commitment_updates', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='adaptation_proposals',
                        to='gie.giesession',
                    ),
                ),
            ],
            options={
                'db_table': 'gie_adaptation_proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gieadaptationproposal',
            index=models.Index(fields=['session', '-created_at'], name='gie_adapta_session_dc4856_idx'),
        ),
        migrations.AddIndex(
            model_name='gieadaptationproposal',
            index=models.Index(fields=['session', 'trigger'], name='gie_adapta_session_65f98d_idx'),
        ),
    ]
