# Generated by Django 6.0 on 2026-03-12 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gie', '0004_giesessionanalytics'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gieadaptationproposal',
            new_name='gie_adaptat_session_72092c_idx',
            old_name='gie_adapta_session_dc4856_idx',
        ),
        migrations.RenameIndex(
            model_name='gieadaptationproposal',
            new_name='gie_adaptat_session_495199_idx',
            old_name='gie_adapta_session_65f98d_idx',
        ),
        migrations.RenameIndex(
            model_name='giesessionanalytics',
            new_name='gie_session_plan_ac_44f6e2_idx',
            old_name='gie_sessio_plan_ac_1efa3a_idx',
        ),
        migrations.RenameIndex(
            model_name='giesessionanalytics',
            new_name='gie_session_last_st_e85751_idx',
            old_name='gie_sessio_last_st_89cebe_idx',
        ),
        migrations.RenameIndex(
            model_name='giesessionanalytics',
            new_name='gie_session_drop_of_0041dc_idx',
            old_name='gie_sessio_drop_of_8f87ce_idx',
        ),
        migrations.RenameIndex(
            model_name='giesessionanalytics',
            new_name='gie_session_created_4ecf7f_idx',
            old_name='gie_sessio_created_9f6d4e_idx',
        ),
    ]
