# Generated by Django 6.0 on 2026-03-25 12:53

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelUsageStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Statistics for this date')),
                ('total_jobs', models.IntegerField(default=0)),
                ('successful_jobs', models.IntegerField(default=0)),
                ('failed_jobs', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('model_usage', models.JSONField(default=dict, help_text="\n        {\n            'claude-sonnet-4': {'jobs': 10, 'tokens': 50000, 'cost': 1.25},\n            'ollama-llama3': {'jobs': 5, 'tokens': 20000, 'cost': 0.0}\n        }\n        ")),
                ('job_type_usage', models.JSONField(default=dict, help_text="\n        {\n            'situation_analysis': {'count': 1, 'tokens': 5000},\n            'goal_generation': {'count': 3, 'tokens': 15000}\n        }\n        ")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Usage Statistics',
                'verbose_name_plural': 'AI Usage Statistics',
                'db_table': 'ai_model_usage_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AIProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('situation_analysis', 'Analyze Current Situation'), ('goal_generation', 'Generate Goals & Roadmap'), ('goal_attributes', 'Extract Goal Attributes'), ('milestone_generation', 'Generate Milestones'), ('task_generation', 'Generate Daily Tasks'), ('habit_suggestion', 'Suggest Habits'), ('progress_analysis', 'Analyze Progress'), ('motivation_generation', 'Generate Motivation')], db_index=True, max_length=50)),
                ('user_raw_text', models.TextField(blank=True, help_text='Raw user input text for AI processing')),
                ('input_data', models.JSONField(blank=True, default=dict, help_text="\n        Structured input for AI processing:\n        {\n            'current_age': 25,\n            'target_age': 30,\n            'situation': '...',\n            'goals': [...],\n            'constraints': [...]\n        }\n        ")),
                ('output_data', models.JSONField(blank=True, default=dict, help_text='AI-generated structured output', null=True)),
                ('raw_ai_response', models.TextField(blank=True, help_text='Complete raw response from AI model')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Job completion progress (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('error_message', models.TextField(blank=True, help_text='Error details if job failed')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum retry attempts allowed')),
                ('ai_model_used', models.CharField(blank=True, help_text="AI model identifier (e.g., 'claude-sonnet-4', 'ollama-llama3')", max_length=100)),
                ('ai_tokens_used', models.IntegerField(default=0, help_text='Total tokens consumed by this job')),
                ('ai_cost_usd', models.DecimalField(decimal_places=4, default=0.0, help_text='Estimated cost in USD', max_digits=10)),
                ('processing_time_seconds', models.FloatField(blank=True, help_text='Total processing time in seconds', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When processing actually started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('priority', models.IntegerField(default=5, help_text='Job priority (1=lowest, 10=highest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context/metadata for the job')),
            ],
            options={
                'verbose_name': 'AI Processing Job',
                'verbose_name_plural': 'AI Processing Jobs',
                'db_table': 'ai_processing_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('situation_analysis', 'Situation Analysis'), ('goal_generation', 'Goal Generation'), ('milestone_generation', 'Milestone Generation'), ('task_generation', 'Task Generation'), ('motivation', 'Motivation Generation')], db_index=True, max_length=50)),
                ('version', models.CharField(default='1.0', help_text='Template version for tracking changes', max_length=20)),
                ('system_prompt', models.TextField(help_text='System prompt that sets AI behavior and context')),
                ('user_prompt_template', models.TextField(help_text='User prompt template with placeholders like {user_input}, {age}, etc.')),
                ('temperature', models.FloatField(default=0.7, help_text='AI temperature setting (0.0 = deterministic, 2.0 = creative)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_tokens', models.IntegerField(default=4000, help_text='Maximum tokens for AI response')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Administrative flag only. Production prompt loading still uses ai/prompts/ assets.')),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this type')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this template has been used')),
                ('success_rate', models.FloatField(default=0.0, help_text='Success rate percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('average_quality_score', models.FloatField(default=0.0, help_text='Average user satisfaction score (1-5)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('notes', models.TextField(blank=True, help_text='Notes about this template version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Prompt Template',
                'verbose_name_plural': 'AI Prompt Templates',
                'db_table': 'ai_prompt_templates',
                'ordering': ['-is_default', '-is_active', 'template_type', '-version'],
            },
        ),
        migrations.CreateModel(
            name='AIReengagementAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('nudge', 'Nudge'), ('escalation', 'Escalation')], db_index=True, max_length=20)),
                ('channel', models.CharField(choices=[('push', 'Push'), ('email', 'Email'), ('none', 'None')], default='none', max_length=10)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('suppressed', 'Suppressed'), ('cooldown_blocked', 'Cooldown Blocked'), ('reengaged_blocked', 'Reengaged Blocked')], db_index=True, max_length=20)),
                ('reason_code', models.CharField(blank=True, max_length=100)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_tier', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'AI Re-engagement Action',
                'verbose_name_plural': 'AI Re-engagement Actions',
                'db_table': 'ai_reengagement_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUserChurnState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_tier', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('inactivity_days', models.IntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('last_scored_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('score_inputs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI User Churn State',
                'verbose_name_plural': 'AI User Churn States',
                'db_table': 'ai_user_churn_states',
                'ordering': ['-last_scored_at'],
            },
        ),
    ]
