# Generated by Django 6.0 on 2026-03-25 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelusagestats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiprompttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompt_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aireengagementaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reengagement_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiuserchurnstate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_churn_state', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aireengagementaction',
            name='churn_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ai.aiuserchurnstate'),
        ),
        migrations.AddIndex(
            model_name='aimodelusagestats',
            index=models.Index(fields=['user', '-date'], name='ai_model_us_user_id_e233e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aimodelusagestats',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='aiprocessingjob',
            index=models.Index(fields=['user', 'status'], name='ai_processi_user_id_2ab0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessingjob',
            index=models.Index(fields=['user', 'job_type'], name='ai_processi_user_id_aaeb47_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessingjob',
            index=models.Index(fields=['status', 'created_at'], name='ai_processi_status_aa4b18_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessingjob',
            index=models.Index(fields=['user', '-created_at'], name='ai_processi_user_id_24b81c_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprompttemplate',
            index=models.Index(fields=['template_type', 'is_active'], name='ai_prompt_t_templat_581781_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprompttemplate',
            index=models.Index(fields=['template_type', 'is_default'], name='ai_prompt_t_templat_0a7a21_idx'),
        ),
        migrations.AddIndex(
            model_name='aiuserchurnstate',
            index=models.Index(fields=['risk_tier', 'last_scored_at'], name='ai_user_chu_risk_ti_2b676c_idx'),
        ),
        migrations.AddIndex(
            model_name='aiuserchurnstate',
            index=models.Index(fields=['user', 'last_scored_at'], name='ai_user_chu_user_id_cbf27e_idx'),
        ),
        migrations.AddIndex(
            model_name='aireengagementaction',
            index=models.Index(fields=['user', 'action_type', 'created_at'], name='ai_reengage_user_id_e38e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='aireengagementaction',
            index=models.Index(fields=['user', 'status', 'created_at'], name='ai_reengage_user_id_93183c_idx'),
        ),
    ]
