# Generated by Django 6.0 on 2026-02-10 07:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelUsageStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Statistics for this date')),
                ('total_jobs', models.IntegerField(default=0)),
                ('successful_jobs', models.IntegerField(default=0)),
                ('failed_jobs', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('model_usage', models.JSONField(default=dict, help_text="\n        {\n            'claude-sonnet-4': {'jobs': 10, 'tokens': 50000, 'cost': 1.25},\n            'ollama-llama3': {'jobs': 5, 'tokens': 20000, 'cost': 0.0}\n        }\n        ")),
                ('job_type_usage', models.JSONField(default=dict, help_text="\n        {\n            'situation_analysis': {'count': 1, 'tokens': 5000},\n            'goal_generation': {'count': 3, 'tokens': 15000}\n        }\n        ")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Usage Statistics',
                'verbose_name_plural': 'AI Usage Statistics',
                'db_table': 'ai_model_usage_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('situation_analysis', 'Situation Analysis'), ('goal_generation', 'Goal Generation'), ('milestone_generation', 'Milestone Generation'), ('task_generation', 'Task Generation'), ('motivation', 'Motivation Generation')], db_index=True, max_length=50)),
                ('version', models.CharField(default='1.0', help_text='Template version for tracking changes', max_length=20)),
                ('system_prompt', models.TextField(help_text='System prompt that sets AI behavior and context')),
                ('user_prompt_template', models.TextField(help_text='User prompt template with placeholders like {user_input}, {age}, etc.')),
                ('temperature', models.FloatField(default=0.7, help_text='AI temperature setting (0.0 = deterministic, 2.0 = creative)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_tokens', models.IntegerField(default=4000, help_text='Maximum tokens for AI response')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this template is currently in use')),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this type')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this template has been used')),
                ('success_rate', models.FloatField(default=0.0, help_text='Success rate percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('average_quality_score', models.FloatField(default=0.0, help_text='Average user satisfaction score (1-5)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('notes', models.TextField(blank=True, help_text='Notes about this template version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Prompt Template',
                'verbose_name_plural': 'AI Prompt Templates',
                'db_table': 'ai_prompt_templates',
                'ordering': ['-is_default', '-is_active', 'template_type', '-version'],
            },
        ),
        migrations.AlterModelOptions(
            name='aiprocessingjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Processing Job', 'verbose_name_plural': 'AI Processing Jobs'},
        ),
        migrations.RemoveField(
            model_name='aiprocessingjob',
            name='row_data',
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='ai_cost_usd',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Estimated cost in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='ai_model_used',
            field=models.CharField(blank=True, help_text="AI model identifier (e.g., 'claude-sonnet-4', 'ollama-llama3')", max_length=100),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='ai_tokens_used',
            field=models.IntegerField(default=0, help_text='Total tokens consumed by this job'),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When processing completed', null=True),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if job failed'),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='input_data',
            field=models.JSONField(blank=True, default=dict, help_text="\n        Structured input for AI processing:\n        {\n            'current_age': 25,\n            'target_age': 30,\n            'situation': '...',\n            'goals': [...],\n            'constraints': [...]\n        }\n        "),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='max_retries',
            field=models.IntegerField(default=3, help_text='Maximum retry attempts allowed'),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional context/metadata for the job'),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='output_data',
            field=models.JSONField(blank=True, default=dict, help_text='AI-generated structured output', null=True),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='priority',
            field=models.IntegerField(default=5, help_text='Job priority (1=lowest, 10=highest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='processing_time_seconds',
            field=models.FloatField(blank=True, help_text='Total processing time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Job completion progress (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='raw_ai_response',
            field=models.TextField(blank=True, help_text='Complete raw response from AI model'),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='Number of retry attempts'),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When processing actually started', null=True),
        ),
        migrations.AlterField(
            model_name='aiprocessingjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='aiprocessingjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiprocessingjob',
            name='job_type',
            field=models.CharField(choices=[('situation_analysis', 'Analyze Current Situation'), ('goal_generation', 'Generate Goals & Roadmap'), ('goal_attributes', 'Extract Goal Attributes'), ('milestone_generation', 'Generate Milestones'), ('task_generation', 'Generate Daily Tasks'), ('habit_suggestion', 'Suggest Habits'), ('progress_analysis', 'Analyze Progress'), ('motivation_generation', 'Generate Motivation')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='aiprocessingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='aiprocessingjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aiprocessingjob',
            name='user_raw_text',
            field=models.TextField(blank=True, help_text='Raw user input text for AI processing'),
        ),
        migrations.AddIndex(
            model_name='aiprocessingjob',
            index=models.Index(fields=['user', 'status'], name='ai_processi_user_id_2ab0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessingjob',
            index=models.Index(fields=['user', 'job_type'], name='ai_processi_user_id_aaeb47_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessingjob',
            index=models.Index(fields=['status', 'created_at'], name='ai_processi_status_aa4b18_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessingjob',
            index=models.Index(fields=['user', '-created_at'], name='ai_processi_user_id_24b81c_idx'),
        ),
        migrations.AlterModelTable(
            name='aiprocessingjob',
            table='ai_processing_jobs',
        ),
        migrations.AddField(
            model_name='aimodelusagestats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiprompttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompt_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aimodelusagestats',
            index=models.Index(fields=['user', '-date'], name='ai_model_us_user_id_e233e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aimodelusagestats',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='aiprompttemplate',
            index=models.Index(fields=['template_type', 'is_active'], name='ai_prompt_t_templat_581781_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprompttemplate',
            index=models.Index(fields=['template_type', 'is_default'], name='ai_prompt_t_templat_0a7a21_idx'),
        ),
    ]
