# Generated by Django 6.0 on 2026-01-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprocessingjob',
            name='user_raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
