# Generated by Django 6.0 on 2026-03-06 17:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aimodelusagestats_aiprompttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUserChurnState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_tier', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('inactivity_days', models.IntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('last_scored_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('score_inputs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_churn_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI User Churn State',
                'verbose_name_plural': 'AI User Churn States',
                'db_table': 'ai_user_churn_states',
                'ordering': ['-last_scored_at'],
            },
        ),
        migrations.CreateModel(
            name='AIReengagementAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('nudge', 'Nudge'), ('escalation', 'Escalation')], db_index=True, max_length=20)),
                ('channel', models.CharField(choices=[('push', 'Push'), ('email', 'Email'), ('none', 'None')], default='none', max_length=10)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('suppressed', 'Suppressed'), ('cooldown_blocked', 'Cooldown Blocked'), ('reengaged_blocked', 'Reengaged Blocked')], db_index=True, max_length=20)),
                ('reason_code', models.CharField(blank=True, max_length=100)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_tier', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reengagement_actions', to=settings.AUTH_USER_MODEL)),
                ('churn_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ai.aiuserchurnstate')),
            ],
            options={
                'verbose_name': 'AI Re-engagement Action',
                'verbose_name_plural': 'AI Re-engagement Actions',
                'db_table': 'ai_reengagement_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aiuserchurnstate',
            index=models.Index(fields=['risk_tier', 'last_scored_at'], name='ai_user_chu_risk_ti_2b676c_idx'),
        ),
        migrations.AddIndex(
            model_name='aiuserchurnstate',
            index=models.Index(fields=['user', 'last_scored_at'], name='ai_user_chu_user_id_cbf27e_idx'),
        ),
        migrations.AddIndex(
            model_name='aireengagementaction',
            index=models.Index(fields=['user', 'action_type', 'created_at'], name='ai_reengage_user_id_e38e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='aireengagementaction',
            index=models.Index(fields=['user', 'status', 'created_at'], name='ai_reengage_user_id_93183c_idx'),
        ),
    ]
