# Generated by Django 6.0 on 2026-03-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aiuserchurnstate_aireengagementaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompttemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Administrative flag only. Production prompt loading still uses ai/prompts/ assets.'),
        ),
    ]
